recipes/gestione/urls.py
from re import search
from django.contrib import admin
from django.urls import path, include
from .views import *
from gestione import views

urlpatterns = [
    # LISTA RICETTE
    path("lista_ricette/", Lista_ricette_views.as_view(), name="listaricette"),
    path("lista_ricette_private/", views.ListaRicettePrivateViews.as_view(), name="listaricetteprivate"),
    path("lista_ricetta_preferite/", views.ListaRicettePreferiteViews.as_view(), name="listaricettepreferite"),

    # DETAIL RICETTA
    path("ricetta/<ricetta_id>/", views.ricetta_detail_view, name="ricetta"),
    
    # CREATE & UPDATE
    path("crea_ricetta_avanzato/", views.ricetta_create_view, name="crearicettaavanzato"),
    path("update_ricetta_avanzato/<pk>/", views.ricetta_update_view, name="updatericettaavanzato"),

    # DELETE
    path("cancella_ricetta/<pk>/", views.ricetta_delete_view, name="deletericetta"),

    # RICERCA E RISULTATI RICERCA
    path("search/", search_advanced, name="search"),
]

recipes/recipes/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

from recipes.initcmds import *
from .views import *
from django.contrib.auth import views as auth_views

from django.conf.urls.static import static
from django.conf import settings

app_name = "gestione"

urlpatterns = [
    path("admin/", admin.site.urls),
    re_path(r"^$|^\/$|^home\/$", Home_page_views.as_view(), name='homepage'),
    
    path("register/", UserCreateView.as_view(), name="register"),
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    
    path('', include('gestione.urls')),

    
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
 
#erase_db()
# init_db()

recipes/gestione/models.py
import datetime
from email.mime import image
from email.policy import default
from random import choices
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

DIFFICOLTA_CHOICES = (("0", ""), ("Bassa", "Bassa"), ("Media","Media"), ("Alta","Alta"))
# DIFFICOLTA_CHOICES = (("1", "Bassa"), ("2","Media"), ("3","Alta"))

PORTATA_CHOICES = (("1", "Antipasto"), ("2", "Primo"), ("3", "Secondo"), ("4", "Dolce"))

class Ricetta(models.Model):
    nome = models.CharField(max_length=50)
    difficoltá = models.CharField(max_length=50, choices=DIFFICOLTA_CHOICES, default="Bassa")
    portata = models.CharField(max_length=50, choices = PORTATA_CHOICES, default="Primo")
    costo = models.IntegerField(default=0)
    tempo_preparazione = models.IntegerField(default=0)
    tempo_cottura = models.IntegerField(default=0)
    porzioni = models.IntegerField(default=1)
    vegetariano = models.BooleanField(default = False)
    vegano = models.BooleanField(default = False)
    gluten_free = models.BooleanField(default = False)
    immagine = models.ImageField(null=True, blank=True)
    procedimento = models.TextField(null=True, blank=True)
    utente = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True, default=None)

    def __str__(self):
        out = self.nome
        return out

    def chi_proprietario(self):
        if self.utente == None:
            return None
        else:
            return self.utente.username
            
    class Meta:
        verbose_name_plural = "Ricette"


UNITA_DI_MISURA_CHOICES = (("grammi", "grammi"), ("unitá", "unitá"), ("ml", "ml"))

class Ingredient(models.Model):
    nome = models.CharField(max_length=50, default=None, null=True)
    quantitá = models.IntegerField(default=None, null=True)
    unita_di_misura = models.CharField(default="grammi", choices=UNITA_DI_MISURA_CHOICES, max_length=50)

    ricetta = models.ForeignKey(Ricetta, on_delete=models.CASCADE, related_name="ingredients")

    def __str__(self):
        if self.nome == None:
            return "ingrediente senza nome"
        return self.nome 

    class Meta:
        verbose_name_plural = "Ingredienti"

PUNTEGGIO_CHOICES = ((0, "-"), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5))

class Recensione(models.Model):
    punteggio = models.IntegerField(default="-", choices=PUNTEGGIO_CHOICES)
    ricetta = models.ForeignKey(Ricetta, on_delete=models.CASCADE, blank=True, null=True, default=None)
    utente = models.ForeignKey(User, on_delete = models.CASCADE, blank=True, null=True, default=None)

    def __str__(self):
        return ("Recensione ricetta: " + str(self.ricetta) + " scritta da utente "+ str(self.utente))

    class Meta:
        verbose_name_plural = "Recensioni"

class RicettePreferite(models.Model):
    ricetta = models.ForeignKey(Ricetta, on_delete=models.CASCADE, blank=True, null=True, default=None)
    utente = models.ForeignKey(User, on_delete = models.CASCADE, blank=True, null=True, default=None)

    def __str__(self):
        return ("Aggiunto " + str(self.ricetta) + " ai preferiti di "+ str(self.utente))




    

recipes/gestione/forms.py
from dataclasses import field
from email.policy import default
from django import forms

from gestione.models import *
from django.forms import formset_factory
from django.forms import BaseInlineFormSet
from django.forms import BaseFormSet

DIFFICOLTA_CHOICES = (("0", ""), ("Bassa", "Bassa"), ("Media","Media"), ("Alta","Alta"))
# DIFFICOLTA_CHOICES = (("0", ""), ("1", "Bassa"), ("2","Media"), ("3","Alta"))

PORTATA_CHOICES = (("0", ""), ("1", "Antipasto"), ("2", "Primo"), ("3", "Secondo"), ("4", "Dolce"))

class SearchForm(forms.Form):
    nome = forms.CharField(label="Nome ricetta", max_length=100, required=False) #min_lenght=3,
    difficolta = forms.ChoiceField(label = "Difficolta", choices=DIFFICOLTA_CHOICES, required = False)
    portata = forms.ChoiceField(label="Pasto", choices=PORTATA_CHOICES, required=False)
    costo_max = forms.IntegerField(label="Costo Massimo", required=False)
    t_prep = forms.IntegerField(label="Tempo di preparazione massimo", required=False)
    is_vegetarian = forms.BooleanField(label = "Vegetariano", required=False)
    is_vegan = forms.BooleanField(label = "Vegano", required=False)
    is_gluten_free = forms.BooleanField(label = "Gluten free", required=False)

class RicettaForm(forms.ModelForm):  
    description_create = "Create a new Ricetta!"
    description_update = "Update a Ricetta!"

    class Meta:
        model = Ricetta
        exclude = ["utente",]


class IngredientForm(forms.ModelForm): 
    class Meta:
        model = Ingredient
        exclude = ('ricetta',)

PUNTEGGIO_CHOICES = ((0, "-"), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5))

class RecensioneForm(forms.ModelForm):
    punteggio = forms.ChoiceField(required=False, choices=PUNTEGGIO_CHOICES)

    class Meta:
        model = Recensione
        exclude = ("utente", 'ricetta')

recipes/gestione/views.py
from django.urls import reverse

from pyexpat.errors import messages
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth.models import User

from django.urls import reverse_lazy
from django.views.generic import *
from .forms import *
from django.contrib.auth.mixins import LoginRequiredMixin
from django.forms import modelformset_factory, inlineformset_factory
from .models import *
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from itertools import chain


# Create your views here.

# Lista ricetta pubbliche e private:
class Lista_ricette_views(ListView):
    model = Ricetta
    template_name = "lista_ricette.html"

    def get_totale_ricette(self):
        count = 0
        for i in Ricetta.objects.all():
            count = count + 1
        return count 

class ListaRicettePrivateViews(LoginRequiredMixin, ListView):
    model = Ricetta
    template_name = "lista_ricette.html"

    def get_queryset(self):
        Data = Ricetta.objects.filter(utente = self.request.user)
        return Data


class ListaRicettePreferiteViews(LoginRequiredMixin, ListView):
    model = Ricetta
    template_name = "lista_ricette.html"

    def get_queryset(self):
        ids_ricette_preferite = RicettePreferite.objects.filter(utente = self.request.user).values_list('ricetta')
        Data = Ricetta.objects.filter(id__in = ids_ricette_preferite)
        return Data


# CREATE & UPDATE: https://www.youtube.com/watch?v=PICYTJqj__o&t=16s
# Per aggiungere ingredienti dinamicamente a una ricetta: https://www.youtube.com/watch?v=JIvJL1HizP4
@login_required
def ricetta_create_view(request):
    form = RicettaForm(request.POST or None, request.FILES or None)
    IngredientFormSet = inlineformset_factory(Ricetta, Ingredient, fields=("nome", "quantitá", "unita_di_misura"), extra=1)

    if request.method == "POST":
        if 'save' or 'aggiungi_ingrediente' in request.POST:
            if form.is_valid():
                obj = form.save(commit = False)
                obj.utente = request.user
                obj.save()
                formset = IngredientFormSet(request.POST or None, instance=form.instance)
                if formset.is_valid():
                    formset.save()
                
            print("Ho eseguito il metodo post")
            # return redirect('listaricette')
            return redirect('updatericettaavanzato', pk = obj.id)
        elif 'back' in request.POST:
            return redirect('listaricette')
        else:
            return redirect('listaricette')
    
    
    if request.method == "GET":
        formset = IngredientFormSet()
        context = {
            "form": form,
            'formset': formset
        }
        print("Ho eseguito il metodo get")
        return render(request, "gestione/create_update_ricetta_avanzato.html", context)

@login_required
def ricetta_update_view(request, pk=None):
    try:
        ricetta = Ricetta.objects.get(id=pk, utente = request.user)
    except Ricetta.DoesNotExist:
        return render(request, "gestione/pagina_di_errore.html")

    form = RicettaForm(request.POST or None, request.FILES  or None, instance=ricetta)
    IngredientFormSet = inlineformset_factory(Ricetta, Ingredient, fields=("nome", "quantitá", "unita_di_misura" ), 
                        extra=1, can_delete=True, can_delete_extra=True, validate_max=0)
    
    if request.method == "POST":
        print("metodo post")
        if 'save' or 'aggiungi_ingrediente' in request.POST:
            print("hai premuto save o aggiugi ingrediente")
            if form.is_valid:
                form.save()
                formset = IngredientFormSet(request.POST or None, instance=ricetta)

                # https://stackoverflow.com/questions/66877831/django-inline-formset-field-required-not-required-setting-in-view
                # modify all the fields
                for form in formset:
                    for field in form.fields.values():
                        field.required = False
                        
                if formset.is_valid():
                    formset.save()
                else: 
                    print("il formset NON é valido: " + formset.errors)

                return redirect('updatericettaavanzato', pk = ricetta.id)
        else:
            print("Sono nell'else")
            return redirect('ricetta', ricetta_id=ricetta.id)
    
    if request.method == "GET":
        formset = IngredientFormSet(instance=ricetta)
        context = {
            "form": form,
            "object": ricetta,
            'formset': formset
        }
        print("Ho eseguito il metodo get")
        return render(request, "gestione/create_update_ricetta_avanzato.html", context)
    
def ricetta_delete_view(request, pk):
    try:
        obj = Ricetta.objects.get(id=pk, utente = request.user)
    except Ricetta.DoesNotExist:
        return render(request, "gestione/pagina_di_errore.html")
    
    if request.method == "POST":
        obj.delete()
        return redirect ("listaricette")

    context = {
        "object" : obj
    }
    return render (request, "gestione/cancella_ricetta.html", context=context)


# RICERCA E RISULTATI RICERCA
# https://www.youtube.com/watch?v=G-Rct7Na0UQ
# https://www.youtube.com/watch?v=vU0VeFN-abU
def search_advanced(request):
    form = SearchForm()

    if request.user.is_authenticated:
        qs = reccomendation_system(request)
    else:
        qs = Ricetta.objects.all()

    if request.method == "POST":
        form = SearchForm(request.POST)
        if form.is_valid():
            nome_query           = form.cleaned_data.get("nome" or None)
            difficolta_query     = form.cleaned_data.get("difficolta" or None)
            portata_query        = form.cleaned_data.get("portata")
            costo_max_query      = form.cleaned_data.get("costo_max")
            t_prep_query         = form.cleaned_data.get("t_prep")
            is_vegetarian_query  = form.cleaned_data.get("is_vegetarian")
            is_vegan_query       = form.cleaned_data.get("is_vegan")
            is_gluten_free_query = form.cleaned_data.get("is_gluten_free")

            # Nome
            if nome_query != '' and nome_query is not None:
                qs = qs.filter(nome__icontains = nome_query)

            # difficoltá
            if difficolta_query != "0" and difficolta_query is not None:
                qs = qs.filter(difficoltá__icontains = difficolta_query)

            # portata
            if portata_query != "0" and portata_query is not None:
                qs = qs.filter(portata__icontains = portata_query)

            # Costo max
            if costo_max_query != '' and costo_max_query is not None:
                qs = qs.filter(costo__lt = costo_max_query)

            # Tempo preparazione
            if t_prep_query != '' and t_prep_query is not None:
                qs = qs.filter(tempo_preparazione__lt = t_prep_query)

            # Vegetariano
            if is_vegetarian_query == True:
                qs = qs.filter(vegetariano = is_vegetarian_query)
            
            # Vegano
            if is_vegan_query == True:
                qs = qs.filter(vegano = is_vegan_query)
    
            # Gluten free
            if is_gluten_free_query == True:
                qs = qs.filter(gluten_free = is_gluten_free_query)

    context = {
        "form" : form,
        "object_list" : qs
    }

    return render (request, "gestione/search_advanced.html", context=context)


# DETAIL RICETTA: 
def ricetta_detail_view(request, ricetta_id):
    ricetta = Ricetta.objects.get(pk=ricetta_id)
    ingredienti = Ingredient.objects.filter(ricetta = ricetta_id).values

    recensioni_della_ricetta = Recensione.objects.filter(ricetta = ricetta)
    numero_recensioni = recensioni_della_ricetta.exclude(punteggio=0).count()
    somma_punteggi = 0
    for recensione in recensioni_della_ricetta:
        if recensione.punteggio != "-":
            somma_punteggi = somma_punteggi + recensione.punteggio
    
    if numero_recensioni != 0: 
        media_recensioni = somma_punteggi / numero_recensioni
    else:
        media_recensioni = 0


    try:
        recensione = Recensione.objects.get(utente = request.user.id, ricetta__id = ricetta_id)
        form = RecensioneForm(request.POST or None, instance=recensione)
    except Recensione.DoesNotExist:
        form = RecensioneForm(request.POST or None, request.FILES  or None)

    if request.method == "POST":
        try:
            recensione = Recensione.objects.get(utente = request.user.id, ricetta__id = ricetta_id)
            if form.is_valid():
                form.save()
                return redirect("ricetta", ricetta_id = ricetta_id)
            else: 
                print("Form non é diventato valido dopo aggiornamento del punteggio")
        except Recensione.DoesNotExist:
            if form.is_valid():
                data = Recensione()
                data.punteggio = form.instance.punteggio
                print("METODO POST: CREAZIONE RECENSIONE: salvo in recensione (instance): " +  str(data.punteggio))
                data.punteggio = form.cleaned_data['punteggio']
                print("METODO POST: CREAZIONE RECENSIONE: salvo in recensione (cleaned_data): " +  str(data.punteggio))
                data.ricetta_id = ricetta_id
                data.utente = request.user
                data.save()
                return redirect("ricetta", ricetta_id = ricetta_id)
            else:
                print("il form non è valido")


    if request.method == 'GET':
        if 'Aggiungi ai preferiti' in request.GET:
            try:
                ricetta_preferita = RicettePreferite.objects.get(utente = request.user, ricetta = ricetta)
                print("Questa ricetta era giá nei preferiti")
            except RicettePreferite.DoesNotExist:

recipes/gestione/templates/gestione/cancella_ricetta.html
{% extends "base.html" %}

{% block content %}

    <h1> Cancellazione della Ricetta </h1>

    <br>

    <form method="post">{% csrf_token %}
        <p>Sicuro di voler cancellare "{{ object }}"? autore {{ object.utente }}</p>
        <input type="submit" value="Conferma">
    </form>

{% endblock %}

recipes/gestione/templates/gestione/create_update_ricetta_avanzato.html
{% extends "base.html" %}

{% block title %} {{ view.form_class.description_update }} {% endblock %}

{% load crispy_forms_tags %}

{% block content %}
    <h1> {{ view.form_class.description_update }} </h1>

    <form method="POST" enctype = "multipart/form-data"> {% csrf_token %}
        {{form|crispy}}
        <h4> Ingredienti </h4>
        {{ formset.management_form }}
        {% for form in formset %}
            {{ form.as_table }} <br> <br>
        {% endfor %}
        <br>
        <input type="submit" class="btn btn-success" name="aggiungi_ingrediente" value="Aggiungi ingrediente">
        <input type="submit" class="btn btn-primary" name="save" value="Modifica e salva">
    </form>
    <br>

    <a href="{% url 'listaricette' %}">
        <input type="submit" class="btn btn-warning" name="back" value="Torna a tutte le ricette">
    </a>
{% endblock %}

recipes/gestione/templates/gestione/pagina_di_errore.html
{% extends "lista_ricette.html" %}

{% block content %}
    ATTENZIONE: Se si arrivato qui ci sono tre possibilitá: 
    <ul>
        <li> Errore nel mio sito web </li>
        <li> Provato a modificare/eliminare una ricetta che non esiste </li>
        <li> Potresti aver fatto il furbetto e aver provato ad modficare/eliminare un ricetta non tua, birichino:</li>

        <div style="width:100%;height:0;padding-bottom:100%;position:relative;">
            <iframe src="https://giphy.com/embed/2zYk0N9ilSztOAPzb0" width="30%" height="30%" style="position:absolute" frameBorder="0" class="giphy-embed" allowFullScreen></iframe>
        </div>>
    </ul>
{% endblock %}

recipes/gestione/templates/gestione/ricetta.html
{% extends "base.html" %}

{% block content %}

    <h1> {{object.nome}} </h1>
    
    {% load static %}<img src="{% static '/img/immagine_di_prova.jpg' %}" width="300" height="160" align=right Hspace="15" Vspace="0" Border="0">
    <ul>
        <li> Difficoltá: {{ object.difficoltá }} </li>
        <li> Regime alimentare: {{ object.regime_alimentare }}</li>
        <li> Portata: {{ object.portata }} </li>
        <li> Costo: {{ object.costo }} € </li>
        <li> Tempo di preparazione: {{ object.tempo_preparazione }} min </li>
        <li> Tempo di cottura: {{ object.tempo_cottura }} min </li>
        <li> Porzioni: {{ object.porzioni }} </li>
    </ul>

    <h3> Preparazione </h3>

{% endblock %}

recipes/gestione/templates/gestione/ricetta_details.html
{% extends "base.html" %}

{% block head %}
<head>
    <meta charset="utf-8"> 
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load static %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" 
          integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href='{% static "/css/style.css" %}'>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
{% endblock %}

{% load crispy_forms_tags %}

{% block content %}
    <div class = myclass>
        {% if user.is_authenticated %}
            <form action="{% url 'ricetta' ricetta.id %}" method="POST" enctype = "multipart/form-data" >  {% csrf_token %}
                {% for field in form %}
                    {{ field.errors }}
                    Dai un voto alla ricetta:  {{ field }}
                {% endfor %}
                <input type="submit" value="Valuta" class="btn btn-primary">
            </form>
        {% endif %}
    </div>
    <div class = myclass2>
        <h1> {{ricetta.nome}} </h1>
    </div>
    <br> <br> <br>
<div>
    {% if ricetta.immagine %}
        {% load static %}<img src="{% static ricetta.immagine.url %}" width="500" height="300" align=right Hspace="15" Vspace="0" Border="0">
    {% endif %}
    <ul>
        <li> Difficoltá: {{ ricetta.get_difficoltá_display }} </li>
        <li> Portata: {{ ricetta.get_portata_display }} </li>
        <li> Costo: {{ ricetta.costo }} € </li>
        <li> Tempo di preparazione: {{ ricetta.tempo_preparazione }} min </li>
        <li> Tempo di cottura: {{ ricetta.tempo_cottura }} min </li>
        <li> Porzioni: {{ ricetta.porzioni }} </li>
        <li> Autore: {{ ricetta.utente }} </li>
    </ul>
      
</div>
    {% if ricetta.vegetariano %}
        <img src={% static "static/img/vetarian_simbol.png" %} width="80" height="80" Hspace="15" Vspace="0" Border="0">        
    {% endif %}
    {% if ricetta.vegano %}
        <img src={% static "static/img/vegan_simbol.png" %} width="80" height="80" Hspace="15" Vspace="0" Border="0">
    {% endif %}
    {% if ricetta.gluten_free %}
        <img src={% static "static/img/gluten_free_simbol.jpg" %} width="80" height="80" Hspace="15" Vspace="0" Border="0">
    {% endif %}


    <br> <br>
    <h4> Ingredienti </h4>
    <ul>
        {% if ingredienti %}
            {% for ingrediente in ingredienti %}
                {% if ingrediente.nome %}
                    <li>{{ ingrediente.nome }} : {{ ingrediente.quantitá }} {{ ingrediente.unita_di_misura }} </li>
                {% endif %}  
            {% endfor %}
        {% else %}
            Non é stato inserito nessun ingrediente in questa ricetta
        {% endif %}
    </ul>

    <h4> Procedimento </h4>
    {{ ricetta.procedimento }}

    <br> <br>
    {% if user.username  == ricetta.utente.username %}
        <a href="{% url 'updatericettaavanzato' ricetta.id %}" class="btn btn-primary"> Modifica Ricetta </a>
        <a href="{% url 'deletericetta' ricetta.id %}" class="btn btn-danger"> Cancella Ricetta </a>
    {% endif %}
    <br> <br> 
    media recensioni : {{ media_recensioni }} <br> ({{ numero_recensioni }} 
    {% if numero_recensioni == 1 %}
        recensione)
    {% else %}
        recensioni)
    {% endif %}
    <br> <br>
    {% if user.is_authenticated %} 
        <form method='get' action='#'> {% csrf_token %}
            <input type="submit" value="Aggiungi ai preferiti" class="btn btn-warning" name="Aggiungi ai preferiti">
        </form>
        <br>
        {% for msg in messages %}        
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                {{ msg }}
              </div>
        {% endfor %}
    {% endif %}
{% endblock %}

recipes/gestione/templates/gestione/search_advanced.html
{% extends "lista_ricette.html" %}

{% block title %} Search Page Form {% endblock %}

{% load crispy_forms_tags %}

<h1>Search Page</h1>

{% block ricerca %} 
    <form action="{% url 'search' %}" method="POST">{% csrf_token %}
        <div class="form-row">
            <div class="form-group col-md-4 mb-0">
              {{ form.nome|as_crispy_field }}
            </div>
            <div class="form-group col-md-2 mb-0">
                {{ form.difficolta|as_crispy_field }}
              </div>
            <div class="form-group col-md-2 mb-0">
                {{ form.portata|as_crispy_field }}
              </div>
            <div class="form-group col-md-2 mb-0">
                {{ form.costo_max|as_crispy_field }}
              </div>
            <div class="form-group col-md-2 mb-0">
              {{ form.t_prep|as_crispy_field }}
            </div>
        </div>
        <div class="form-row">
            <div class="horizontalgap" style="width:120px">
                {{ form.is_vegetarian|as_crispy_field }}
            </div>
            <div class="horizontalgap" style="width:100px">
                {{ form.is_vegan|as_crispy_field }}
            </div>
            <div class="horizontalgap" style="width:200px">
                {{ form.is_gluten_free|as_crispy_field }}
            </div>
        </div>
        <input type="submit" class="btn btn-success" value="Search" name='q'>
    </form>
{% endblock %}

    

recipes/gestione/templates/gestione/search_page.html
{% extends "base.html" %}

{% block title %} Search Page Form {% endblock %}

{% load crispy_forms_tags %}

{% block content %}
    <h1>Search Page</h1>
    
    <form action="{% url 'search' %}" method="POST">{% csrf_token %}
        {{form|crispy}} <br>
    <input type="submit" value="Search" name='q'> </form>

{% endblock %}

recipes/gestione/templates/gestione/update_ricetta_avanzato.html
{% extends "base.html" %}

{% block title %} {{ view.form_class.description_update }} {% endblock %}

{% load crispy_forms_tags %}

{% block content %}
    Questo é il file "update_ricetta_avanzato.html"
    <h1> {{ view.form_class.description_update }} </h1>

    <form method="POST"> {% csrf_token %}
        {{form|crispy}}
        {{ formset.as_p}}    
        <input type="submit" name="save" value="Modifica e salva">
        <input type="submit" name="back" value="Torna indietro">
    </form>
{% endblock %}